user = User.create(email: 'dan@example.com', password: "earthsource", name: "Dan De Lion", bio: "Forager, Herbalist, and Teacher at Back to Nature. BTN provides a safe and healing teaching bridge for individuals and communities to recognize Nature as a continual and abundant provider of nourishment, medicine, and spiritual connection.")
user.pic.store!(File.open(File.join(Rails.root, 'Dan_Farella.jpg')))
user.save!

user.events.create(title: 'Winter Survival Foraging', location: 'Manasquan Resevoir - 311 Windeler Road, Howel 07731', date: Date.new(2013, 8, 12), time: '2:00 pm',  description: 'Join Dan as he helps to uncover the skills necessary to survive during an emergency, even in the coldest conditions.  We’ll explore the surrounding areas for food and medicine that can be utilized in a situation such as we saw with Hurricane Sandy. We’ll discover where and how to track and catalogue medicinal foods, shelter items, utilitarian plants, and how to purify and acquire water from the landscape. DRESS WARM - Layers of wool recommended. Bring a camera and notebook for recording the plants we find.
Meet at the Visitor Center Parking lot - Windeler Rd. Entrance.  When you enter, go to the parking lot on the right and you’ll see the visitors center building.')

user.events.create(title: 'Plant Walk with Wildman Steve Brill', location: 'Prospect Park Entrance', date: Date.new(2013, 11, 30), time: '11:30 am',  description: 'This Saturday I will be headed to Wildman Steve Brills Plant walk in Prospect Park as a guest forager and student. I thought it would be nice to go on an Return to Nature Class Trip. Come join in the re-skilling! RSVP REQUIRED - CALL (914) 835-2153 at least 24 hours in advance to reserve a place and SEE the info at this site... http://www.wildmanstevebrill.com' )
user.events.create(title: 'Wild Foraging for Food and Medicine', location: 'Marquand Park Entrance - Lovers Ln, Princeton, NJ 08540', date: Date.new(2013, 10, 11), time: '2:00 pm',  description: 'Come join in foraging for a wild salad and learn about nutritional, edible, and medicinal plants growing in any yard or park. We will harvest together and sample some of the wonderful weeds. There are only a few more weeks of what is deemed the "second spring", so come join in the foraging feast! Please bring a camera and notebook for recording the plants we find' )

user.events.create(title: 'Plant walk @ Brooklyn Permaculture Fest', location: 'Old Stone House - 336 3rd St, Brooklyn, NY 11215', date: Date.new(2013, 01, 11), time: '11:30 am',  description: 'Join Dan for an insightful plant walk at The Brooklyn Permaculture Festival!   We will walk and explore the lands around the Old Stone House, and discuss medicinal applications of many of the plants growing there. You will leave with a stronger connection to Nature, and a grounded awareness in some of the ways that herbs, in their fresh, and dry states, can be harnessed for healing and well-being. Bring a camera and notebook for recording the plants we find' )